### ISSUE TITLE
Class description not matching Funnel server return

### ISSUE THREAD

**Issue by kellrott** [ohsu-comp-bio/py-tes#13]
Stack trace:
```
(venv)RJHB298:nci-cptac-dream ellrott$ ./run_training.py feature.matrix label.matrix pathway.matrix
Traceback (most recent call last):
  File "./run_training.py", line 47, in <module>
    scores = ts.run(do_learning, feat_rna, label_prot, matrix_isect, GENE)
  File "build/bdist.macosx-10.10-intel/egg/tesseract/tesseract.py", line 164, in run
  File "build/bdist.macosx-10.10-intel/egg/tes/client.py", line 48, in create_task
  File "build/bdist.macosx-10.10-intel/egg/tes/utils.py", line 70, in unmarshal
TypeError: __init__() got an unexpected keyword argument 'tasks'
```

Looks like 'tasks' is in the code returned by the server, but not in the CreateTaskResponse class declaration.

Is this a Funnel server issue?

**Comment by buchanae** [comment]
This script is working for me:
```
from tes.client import HTTPClient
from tes.models import Task, Executor

t = Task(
    executors=[
        Executor(
            image_name="alpine",
            cmd=["echo", "hello"]
        )
    ]
)
c = HTTPClient("http://localhost:8000")
print c.create_task(t)
```

I doubt this is a Funnel issue. I suspect this function: https://github.com/ohsu-comp-bio/py-tes/blob/master/tes/utils.py#L36

**Comment by adamstruck** [comment]
The issue is funnel related: https://github.com/ohsu-comp-bio/funnel/issues/282

Could be also be mitigated on the client side by removing trailing `/` from TES url.
