### ISSUE TITLE
Models should be serializable by json.dump

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/py-tes#20]
`json.dump` is the standard way of encoding json in python. These models should support that standard.

Somewhat related, `json.dumps(task)` fails with:
```
Traceback (most recent call last):
  File "collect-status.py", line 1650, in <module>
    main()
  File "collect-status.py", line 23, in main
    print taskfile, taskid, json.dumps(task, indent=True)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

**Comment by uniqueg** [comment]
I'm not sure it's worth the effort. Calling `.as_json()` on a model instance seems good enough to me. Given that this is now five years old, not entirely trivial to implement, and nobody else asked for it, I would propose to close this issue.

**Comment by kellrott** [comment]
I agree
